{% set name = "pycvodes" %}
{% set version = "0.11.14" %}
{% set sha256 = "50cde869024bc2f5f0455ea81222165a1ec0cb442131d4ea8ae024321503c61a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true        # [win and not py>=35]
  features:

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapack
    - sundials
    - python
    - setuptools
    - pip
    - numpy
  run:
    - sundials
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pycvodes
  requires:
    - pytest

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python wrapper around cvodes (from the sundials library)'
  doc_url: https://bjodah.github.io/{{ name }}/latest


extra:
  recipe-maintainers:
    - bjodah
