travis:
  secure:
    BINSTAR_TOKEN: cH13a2Inx40EwCtgSDJ9Z9FfASr+rRJMZzArwKGDX+swALGW78W720Oe73LfgMA6ngytWO979L+EXgM0anXBtkDTyfsSM91YDuqIHAtgkJIWz2r21/3bfPZ6/0Cd1lXtIDPl7+EUnb84xzLksV/CTYI6WKTL6LMKCeORCHRAyTznRtVmwmvgRfPfyRrIoW/lRByE5VIWOtKUcjPCnqhLw7UKJJBupfQzHpUQ9YdlrbpiHn1Y0rIP3ef8RPex4BXJPUdJfQEnZYRpV4ii7KLKEIZfaP2RsAt0TEI4Y1wCbb00IJ0wd5mtzIWpunfEekf/rAWRfbMuU7JoKQMi36tHrr/RqLF0IGcwBvmjxZyQIdE8i18lJsAP/c2UvDB5i9cnD6vaFKYbZPir5NT8RmSLvWwGTTdYRufCY9TxecLi7Qz7ckJv5Ih/q2X+RsyHAbunBjAg3LXjFw+debBIEGLLiF+pP8L4KMQ1bpGp5M96oKeD5Y/Z4r/z/r+7ljfirn4IddO5Ss0aGlmW+RB6RHR24bCbeDDDAD67DjbkbzipRV8zcqOLmYtuI2Uonkf8/x/wpxXOKR4wkYr/lWlDProHbxnTiFaIykzCUZWKtTpCJFWdlhEKvgo4GNX6oIwMcNzBJNoq/lC/qQuySLZFqrFmWp6hvYLuUOi7Oko7Up5Haaw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
